services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio_website.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
